// <auto-generated />
using Backend_FIAP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_FIAP.Migrations
{
    [DbContext(typeof(FiapDbContext))]
    [Migration("20240512143034_dbCreate")]
    partial class dbCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend_FIAP.Models.AlunoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("aluno");
                });

            modelBuilder.Entity("Backend_FIAP.Models.Aluno_TurmaModel", b =>
                {
                    b.Property<int>("aluno_id")
                        .HasColumnType("int");

                    b.Property<int>("turma_id")
                        .HasColumnType("int");

                    b.Property<int>("alunoid")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("turmaid")
                        .HasColumnType("int");

                    b.HasKey("aluno_id", "turma_id");

                    b.HasIndex("alunoid");

                    b.HasIndex("turmaid");

                    b.ToTable("aluno_turma");
                });

            modelBuilder.Entity("Backend_FIAP.Models.TurmaModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("ano")
                        .HasColumnType("int");

                    b.Property<string>("curso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("turma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("turma");
                });

            modelBuilder.Entity("Backend_FIAP.Models.Aluno_TurmaModel", b =>
                {
                    b.HasOne("Backend_FIAP.Models.AlunoModel", "aluno")
                        .WithMany()
                        .HasForeignKey("alunoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_FIAP.Models.TurmaModel", "turma")
                        .WithMany()
                        .HasForeignKey("turmaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aluno");

                    b.Navigation("turma");
                });
#pragma warning restore 612, 618
        }
    }
}
